---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---



```{r}

## get required packages
library(SummExpDR)
library(DESeq2)
library(SummarizedExperiment)
## Setup directories
top.dir <- '/home/owenwhitley/projects/su2c_v2/'
scripts.dir <- file.path(top.dir, 'scripts/RNA/analysis')
RNA.results.dir <- file.path(top.dir, 'results/RNA')
original.GSC.results.dir <- file.path(RNA.results.dir, 'RNA_GSCs_clustering')
analysis.results.dir <- file.path(RNA.results.dir, 'RNA_GSCs_PC2_GSEA')

overwrite <- T
if (dir.exists(analysis.results.dir) && overwrite) {
  system(paste('rm -rf', analysis.results.dir))
}

if (!dir.exists(analysis.results.dir)) {
  dir.create(analysis.results.dir)
}

```


``` {r}
load(file.path(original.GSC.results.dir, 'RNA_GSC_obj.RData'))

for (i in 2:3) {
  PCX <- SummExpDR::getLoadings(RNA.GSC.obj, key = 'PCA', dims_use = paste0('PC', i))
  PC_names <- colnames(PCX)
  PCX <- as.vector(PCX)
  names(PCX) <- PC_names
  PCX <- PCX[order(PCX, decreasing = T)]
  rank.table <- data.frame(genes = names(PCX), PC_loading = PCX)
  fname <- paste0('PC', i, '.rnk')
  rankfile.path <- file.path(analysis.results.dir, fname)
  write.table(rank.table, file = rankfile.path, 
              sep = "\t", quote = F, row.names = F)
  enrich_GSEA(gsea_rank_list_path = rankfile.path,
              gsea_analysis_name = paste0('RNA_GSCs_PC', i),
              gsea_out = analysis.results.dir,
              gsea_gmx = NULL)

}


```

``` {r}
Sys.time()
sessionInfo()
```
