---
title: "CRISPR Screen, GSCs. GSEA on difference in average qBF for Dev and IR Lines"
output: html_notebook
---



```{r}
library(SummExpDR)

top_dir <- '~/projects/su2c_v2/'
crispr_data <- readRDS(file.path(top_dir, '/data/raw/CRISPR/CRISPR_Avg_Diff_Matrix.rds'))

crispr_data
gmt_file <- file.path(top_dir, '/data/raw/gmt_files/baderlab_gmts/Human_GO_AllPathways_no_GO_iea_April_01_2018_symbol.gmt')

crispr_data
```

``` {r}

# make diff negative so that genes that are more essential in Developmental cells show up at top of list
rank_table <- data.frame(gene = rownames(crispr_data), Diff = -crispr_data$Diff)
rank_table

output_dir <- file.path(top_dir, 'results/CRISPR_screens/CRISPR_avg_qBF_Dev_v_IR_GSCs')
if (!dir.exists(output_dir)) {
  dir.create(output_dir)
}

rnk_file <- file.path(output_dir, 'CRISPR_avg_qBF_Dev_v_IR_GSCs.rnk')
write.table(rank_table, 
            file = rnk_file, 
            quote = FALSE, 
            sep = '\t', 
            row.names = FALSE, 
            col.names = TRUE)

SummExpDR::enrich_GSEA(gsea_rank_list_path = rnk_file, 
                      gsea_analysis_name = 'avg_qBF_Diff', 
                      gsea_gmx = gmt_file,
                      gsea_min_gs_size = 15, gsea_max_gs_size = 200,
                      gsea_out = output_dir)

```

``` {r}
sessionInfo()
```