---
title: "Examine correlation between pairs of variables"
output:
  html_document:
    df_print: paged
    toc: true
    toc_depth: 5
params:
  inp_data: '~/projects/su2c_v2/data/preprocessed/scRNA/GSCs_Tumour_combined/BTSC_Tumour_combined_obj_seurat_subset.rds'
  feats_plot: 'culture_cond'
  cor_pairs: 'NULL'
  filter_by: 'culture_cond'
  method: 'pearson'
  pt_size: 1
---

# Overview
For combined GSCs + Tumours we're wondering if we see an anticorrelation of the RNA GSC c1 and RNA GSC c2 signatures, which are obtained throught the AUCell
scoring method.

# Setup

```{r}
source('./laura_SU2C_GBM_GSCs_combined_explore_helpers.R')

for (i in 1:length(params)) {
  param.i <- names(params)[i]
  assign(param.i, params[[i]])
}


if (is.character(inp_data)) {
      # we only load data in from file for testing/debugging purposes.
      # inp_data should generally be a Seurat object that is fully preprocessed 
      # as outlined in 'seurat_pipeline' function in helper functions,
      # with PCA calculated
      if (file.exists(inp_data)) {
        inp_data <- readRDS(inp_data)
      } else {
        stop('File for input data does not exist')
      }
}

if (cor_pairs == 'NULL') {
  cor_pairs <- list(c('RNA.GSC.c1_AUC', 'RNA.GSC.c2_AUC'))
}
```

# Correlation plots

``` {r, results='asis', message=FALSE, warning=FALSE}
# filter_by <- c('Stage', 'culture_cond')
# feats_plot <- c('RNA.GSC.c1_AUC', 'RNA.GSC.c2_AUC', 'C1_C2_diff')

# add filter criteria to features to plot
feats_plot <- union(filter_by, feats_plot)

# for every pair of variables which we want to measure correlation for
for (pair_use in cor_pairs) {
  if (length(pair_use) != 2) {
    stop('cor_pairs, if specified, should be a list of character vectors (each length 2). character vectors should denote pairs of variables to be correlated')
  }
  pair_name <- paste(pair_use[1], 'vs', pair_use[2])
  cat(paste('\n##', pair_name, '\n'))
  # for each filter criterion
  for (filter_criterion in filter_by) {
    cat(paste('\n###', filter_criterion, '\n'))
    class_values <- unique(Seurat::FetchData(inp_data, vars.all = filter_criterion)[,1])
    if (is.numeric(class_values)) {
      if (is.integer(class_values)) {
        class_values <- as.character(class_values)
      } else {
        stop('cannot have floating point or double valued variables for filter criteria')
      }
    } else {
      class_values <- as.character(class_values)
    }
    # plot all cells as well as cells filtered by a class in the filter criterion
    for (filter_class in c('all', class_values)) {
      cat(paste('\n####', filter_class, '\n'))
      if (filter_class == 'all') {
        filter_class <- class_values
      }
      for (feat in feats_plot) {
        p <- corplot_2_var(obj = inp_data, var1 = pair_use[1], var2 = pair_use[2], 
                           filter_by = filter_criterion, filter_class = filter_class, 
                           color_by = feat, legend_pt_size = 5.0, method = method, pt.size = pt_size)
        print(p)
        rm(p)
        gc(full = TRUE)
        cat('\n')
      }
      cat('\n\n')
    }
  }
  
}

```

# Session Info

``` {r}
Sys.time()
sessionInfo()

```