---
title: "Make Ranked Lists of Correlated Genes"
output: html_notebook
params:
  seurat_obj: 'NULL'
  output_dir: '../../results/scRNA/AUC_score_correlation'
  outfile_prefix: 'GBM_GSCs_combined'
---

# Overview

Want to assess correlation of various gene signatures that Laura Richards (Pugh Lab) scored the GBM/GSC scRNA data for (AUCell)
with injury response, developmental, glioma stem cell, + astrocyte AUCell scores

```{r}
# assign param values
for (i in 1:length(params)) {
  assign(names(params)[i], params[[i]])
}

# make output directory if does not exist
if (!dir.exists(output_dir)) {
  dir.create(output_dir)
}

# by default load in a GSC/Tumour combined seurat object
if (!class(seurat_obj) == 'seurat') {
  seurat_obj <- readRDS('../../data/preprocessed/scRNA/GSCs_Tumour_combined/laura_BTSC_Tumour_combined_Oct_2019.rds')
}
meta_data <- seurat_obj@meta.data
meta_data_scores <- meta_data[,grep('_AUC$', colnames(meta_data))]

# rename RNA.GSC.c1_AUC and RNA.GSC.c2_AUC to Developmental_AUC + Injury_Response_AUC
colnames(meta_data_scores)[grep('RNA.GSC.c1_AUC', colnames(meta_data_scores))] <- 'Developmental_AUC'
colnames(meta_data_scores)[grep('RNA.GSC.c2_AUC', colnames(meta_data_scores))] <- 'Injury_Response_AUC'

# function to calculate correlation of 1 variable with all other variables in data.frame.
# by default use spearman correlation
get_cor_table <- function(df, var1, method = 'spearman') {
  stopifnot(is.data.frame(df))
  var1_vals <- df[,var1]
  df_subs <- df[,-which(colnames(df) == var1)]
  cor_result <- as.numeric(cor(var1_vals, df_subs, method = method))
  suppressWarnings({cor_pval <- apply(as.matrix(df_subs), MARGIN = 2, FUN = function(x) {
    return(cor.test(var1_vals, x, method = method)$p.value)
  })})
  p_adj <- p.adjust(cor_pval, method = 'BH')
  output_df <- data.frame(name = colnames(df_subs), correlation = cor_result, pval = cor_pval, fdr = p_adj)
  output_df <- output_df[order(output_df$correlation, decreasing = TRUE),]
  rownames(output_df) <- 1:nrow(output_df)
  return(output_df)
}

# get correlation tables
cor_Injury_Response <- get_cor_table(meta_data_scores, 'Injury_Response_AUC')
cor_Developmental <- get_cor_table(meta_data_scores, 'Developmental_AUC')
cor_glioma_stem_cell <- get_cor_table(meta_data_scores, 'glioma.stem.cell_AUC')
cor_cahoy_astro <- get_cor_table(meta_data_scores, 'cahoy_astrocyte_AUC')

# display results

cor_Injury_Response

cor_Developmental

cor_glioma_stem_cell

cor_cahoy_astro

# save results
write.csv(cor_Injury_Response, file.path(output_dir, paste0(outfile_prefix, '_Injury_Response_correlation.csv')))
write.csv(cor_Developmental, file.path(output_dir, paste0(outfile_prefix, '_Developmental_correlation.csv')))
write.csv(cor_glioma_stem_cell, file.path(output_dir, paste0(outfile_prefix, '_glioma_stem_cell_correlation.csv')))
write.csv(cor_cahoy_astro, file.path(output_dir, paste0(outfile_prefix, '_cahoy_astro_correlation.csv')))
```

``` {r}
sessionInfo()
```
