---
title: "GBM GSCs combined exploration, Dimensionality Reduction Plots"
output:
  html_document:
    df_print: paged
    toc: true
params:
  filter_by: 'NULL'
  filter_class: 'NULL'
  inp_data: '~/projects/su2c_v2/data/preprocessed/scRNA/GSCs_Tumour_combined/BTSC_Tumour_combined_obj_seurat_subset.rds'
  feats_plot: 'NULL'
  reductions_plot: 'pca'
  dims_use_mapping: 'NULL'
  
---

# Setup

## Load data, source functions

```{r}
library(Matrix)
library(Seurat)
library(ggplot2)
library(SummarizedExperiment)
library(R.devices)

source('./laura_SU2C_GBM_GSCs_combined_explore_helpers.R')

# preproc_dir <- '~/projects/su2c_v2/data/preprocessed/scRNA/GSCs_Tumour_combined'
# data_fname <- 'BTSC_Tumour_combined_obj.RData'



# tryCatch({load(file.path(preproc_dir, data_fname))},
#          error = function(e) {
#            stop('error in loading preprocessed data. try running laura_SU2C_GBM_GSCs_combined_preprocess.R first')
#            })
```

## setup params

``` {r}
## setup params

for (i in 1:length(params)) {
  param.i <- names(params)[i]
  assign(param.i, params[[i]])
}

if (is.character(filter_by)) {
  if (filter_by == 'NULL') {
    filter_by <- NULL
  }
} else if (!is.null(filter_by)) {
  stop('filter_by must be character vector or NULL')
}

if (is.character(filter_class)) {
  if (filter_class == 'NULL') {
    filter_class <- NULL
  }
} else if (!is.null(filter_class)) {
  stop('filter_class must be character vector or NULL')
}

if (is.character(inp_data)) {
      # we only load data in from file for testing/debugging purposes.
      # inp_data should generally be a Seurat object that is fully preprocessed 
      # as outlined in 'seurat_pipeline' function in helper functions,
      # with PCA calculated
      if (file.exists(inp_data)) {
        inp_data <- readRDS(inp_data)
      } else {
        stop(paste('file', inp_data, 'does not exist'))
      }
}
stopifnot(is(inp_data, 'seurat'))

# setup mapping of dim reduction names to dims to use for each dim reduction
if (dims_use_mapping == 'NULL') {
  # dims_use_mapping should be a named list of lists, with each 'sublist' containing pairs of 
  # dimensions to plot
  dims_use_mapping <- list(pca = list(c(1,2), c(1,3)),
                           tsne = list(c(1,2)),
                           harmony = list(c(1,2)),
                           mnn = list(c(1,2)),
                           fastmnn = list(c(1,2), c(2,3)))
} else {
  if (!is.list(dims_use_mapping)) {
    stop('dims_use_mapping, if specified, must be a list')
  }
}
if (!all(reductions_plot %in% names(dims_use_mapping))) {
  stop('all reductions plotted must be in names of dim_use_mapping')
}

```

## if we're using pca, we're interested in what the std dev of each PC is, as well as loadings

``` {r}
use_pca <- 'pca' %in% reductions_plot
```

# Explore

``` {r}
# show variable genes
# FindVariableGenes(inp_data, do.recalc = FALSE, do.plot = TRUE)

if (feats_plot == 'NULL') {
  # define features to plot
  # genes_of_interest <- c('NES', 'GFAP', 'OLIG1', 'OLIG2', 'CD44', 'SOX2', 'ALDH1L1',
  #                        'MET', 'STMN1', 'DLL3', 'COL5A1', 'ANXA1', 'VIM', 'SERPINA3',
  #                        'MKI67', 'CDK1', 'PTX3', 'IL6', 'IL6R', 'STAT3', 'JAK1', 'JAK2', 'JAK3')
  genes_of_interest <- c('GFAP', 'SOX2', 'SOX10')
  scores_of_interest <- colnames(inp_data@meta.data)[grep('AUC$', colnames(inp_data@meta.data))]
  score_regex <- paste('RNA.GSC.c[1-2]',
                       'glioma.stem.cell',
                       'Zhong_NPCs_upreg',
                       'nowakowski_(RG-early|IPC-div[1-2])',
                       'cahoy', 
                       'a[1-2].astro',
                       'tirosh',
                       sep = '|')
  scores_of_interest <- scores_of_interest[grep(score_regex, scores_of_interest)]
  numeric_feats <- c('CC.Difference', 'G2M.Score', 'S.Score',
                     genes_of_interest, scores_of_interest,
                     'PC1', 'PC2', 'PC3')
  numeric_feats <- numeric_feats[order(numeric_feats)][1:3]
  categorical_feats <- c('SampleType', 'seurat_clusters', 'culture_cond', 'SampleID')
  categorical_feats <- categorical_feats[order(categorical_feats)]
  feats_plot <- c(categorical_feats, numeric_feats)
  
}

# set numeric and categorical feats
numeric_feat_inds <- which(as.logical(lapply(FetchData(inp_data, vars = feats_plot), FUN = is.numeric)))
numeric_feats <- feats_plot[numeric_feat_inds]
categorical_feats <- feats_plot[-numeric_feat_inds]
```


``` {r, results='asis'}
for (dr_name in reductions_plot) {
  dr_name_upper <- toupper(dr_name)
  cat(paste('##', dr_name_upper, '\n'))
  dims_use_list <- dims_use_mapping[[dr_name]]
  
  if (dr_name == 'pca') {
    print(Seurat::PCElbowPlot(inp_data))
    cat('\n\n')
  }
  
  for (i in 1:length(dims_use_list)) {
    dims_i <- dims_use_list[[i]]
    cat(paste('###', paste(dr_name_upper, dims_i[1]), paste(dr_name_upper, dims_i[2]), '\n'))
    # make contour plots on the given dimensionality reduction
    for (var_name in categorical_feats) {
      try({
        p <- make_contour_plot(inp_data, dim1 = dims_i[1], dim2 = dims_i[2], 
                             reduction_use = dr_name, split_by = var_name, bins = 3, 
                             density_ceiling = 0.7)
        print(p)
      })
    }
    # do scatterplots colored by feature for the selected reduced dims
    try({
      make_dr_plots(inp_data, dim1 = dims_i[1], dim2 = dims_i[2], reduction.use = dr_name, 
                  feats_plot = feats_plot, legend_pt_shape = 16, legend_pt_size = 10,
                  filter_by = filter_by, filter_class = filter_class)
    })
    cat('\n')
    cat('\n')
  }
}

```




# SessionInfo

``` {r}
sessionInfo()
```
