---
title: "Dimensionality Reduction Plots for Seurat Object"
output:
  html_document:
    df_print: paged
    toc: true
    toc_depth: 5
params:
  inp_data: '~/projects/su2c_v2/data/preprocessed/scRNA/Bhaduri_2020/bhaduri_2020_tumor_seurat_scored.rds'
  x_axis_var: 'NULL'
  y_axis_var: 'NULL'
---



```{r}
suppressPackageStartupMessages({source('laura_SU2C_GBM_GSCs_combined_explore_helpers.R')})
library(ggplot2)
library(ggrepel)
library(pheatmap)
for (i in 1:length(params)) {
  param.i <- names(params)[i]
  assign(param.i, params[[i]])
}


if (is.character(inp_data)) {
      # we only load data in from file for testing/debugging purposes.
      # inp_data should generally be a Seurat object that is fully preprocessed 
      # as outlined in 'seurat_pipeline' function in helper functions,
      # with PCA calculated
      if (file.exists(inp_data)) {
        inp_data <- readRDS(inp_data)
      } else {
        stop('File for input data does not exist')
      }
}
```

``` {r}
stacked_barcharts(inp_data@meta.data, x_axis_var, y_axis_var)
```

