---
title: "Dimensionality Reduction Plots for Seurat Object"
output:
  html_document:
    df_print: paged
    toc: true
    toc_depth: 5
params:
  inp_data: '~/projects/su2c_v2/data/preprocessed/scRNA/Bhaduri_2020/bhaduri_2020_tumor_seurat_scored.rds'
  feats_plot: 'Developmental_AUC'
  dr_use: 'NULL'
  dims_plot: 'NULL'
  top_loadings: 50
  pt_size: 3
  legend_pt_size: 5
  loadings_txt_size: 2
  split_by: 'NULL'
  eps: 3.0
  density_ceiling: 0.80
  bins: 10
  grid_dist: 1.0
---

# Load Data, setup params

```{r, results='asis'}
suppressPackageStartupMessages({source('laura_SU2C_GBM_GSCs_combined_explore_helpers.R')})
library(ggplot2)
library(ggrepel)
library(pheatmap)
for (i in 1:length(params)) {
  param.i <- names(params)[i]
  assign(param.i, params[[i]])
}


if (is.character(inp_data)) {
      # we only load data in from file for testing/debugging purposes.
      # inp_data should generally be a Seurat object that is fully preprocessed 
      # as outlined in 'seurat_pipeline' function in helper functions,
      # with PCA calculated
      if (file.exists(inp_data)) {
        inp_data <- readRDS(inp_data)
      } else {
        stop('File for input data does not exist')
      }
}

if (split_by == 'NULL') {
  split_by <- NULL
}

if (dr_use == 'NULL') {
  # dr_use <- c('pca', 'tsne', 'dm')
  dr_use <- 'pca'
}

if (dims_plot == 'NULL') {
  dims_plot <- list(pca = list(c(1,2), c(2,3)),
                    tsne = list(c(1,2)),
                    dm = list(c(1,2)))
}

cat('\n\n## feats_plot\n\n')
print(feats_plot)
cat('\n\n## dr_use\n\n')
print(dr_use)
cat('\n\n## dims_plot\n\n')
print(dims_plot)
```

``` {r, results='asis'}
for (dr_name in dr_use) {
  try({
    cat(paste('\n\n#', dr_name,'\n\n'))
    dr_sdev <- Seurat::GetDimReduction(inp_data, reduction.type = dr_name, 'sdev')
    key <- Seurat::GetDimReduction(inp_data, reduction.type = dr_name, 'key')
    all_dims <- sort(unique(unlist(dims_plot[[dr_name]])))
    gene_loadings <- Seurat::GetDimReduction(inp_data, reduction.type = dr_name, 'gene.loadings')
    
    if (is.numeric(dr_sdev) && (length(dr_sdev) > 0)) {
      cat('\n\n## Elbow Plot\n\n')
      plot(dr_sdev, xlab = key, ylab = 'std dev')
    }
    if (nrow(gene_loadings) > 0 && ncol(gene_loadings > 0)) {
      gene_loadings <- gene_loadings[,all_dims]
      cat('\n\n## Loadings\n\n')
      knitr::opts_chunk$set(fig.width = 4)
      knitr::opts_chunk$set(fig.height = 7)
      # all_loadings_plot <- c()
      for (i in 1:ncol(gene_loadings)) {
        cat(paste('\n\n###', colnames(gene_loadings)[i], '\n\n'))
        loadings_i <- gene_loadings[,i]
        top_n_up <- names(sort(loadings_i)[1:top_loadings])
        top_n_down <- names(sort(loadings_i, decreasing = TRUE)[1:top_loadings])
        loadings_plot <- sort(loadings_i[c(top_n_up, top_n_down)])
        # all_loadings_plot <- c(all_loadings_plot, top_n_up, top_n_down)
        # print(knitr::kable(data.frame(loading = loadings_plot, row.names = names(loadings_plot))))
        # plot(loadings_plot, pch = 16, xlab = 'index', ylab = 'loading')
        # text(loadings_plot, labels = names(loadings_plot), adj = c(1,1), cex = loadings_txt_size)
        data_plot <- data.frame(index = 1:length(loadings_plot), loadings = loadings_plot, gene = names(loadings_plot))
        p <- ggplot(data = data_plot, aes(index, loadings)) +
          geom_point(aes(color = loadings)) + geom_text_repel(aes(label = gene), size = loadings_txt_size) +
          scale_color_gradient2()
        print(p)
        # print(pheatmap(inp_data@scale.data[names(loadings_plot),], fontsize_row = loadings_txt_size, show_colnames = FALSE, cluster_cols = FALSE))
      }
      # all_loadings_plot <- unique(all_loadings_plot)
      # print(pheatmap(gene_loadings[all_loadings_plot,], fontsize_row = loadings_txt_size))
      # cat(paste0('\n\n union of top and bottom ', top_loadings,' loadings for selected dimensions\n\n'))
    }
    knitr::opts_chunk$set(fig.width = 7)
    knitr::opts_chunk$set(fig.height = 7)
    for (dr_pair in dims_plot[[dr_name]]) {
      dim1 <- dr_pair[1]
      dim2 <- dr_pair[2]
      cat(paste('\n\n##', paste(paste0(key, c(dim1, dim2)), collapse = ' '), '\n\n'))
      
      if (!is.null(split_by)) {
        classes_split <- unique(inp_data@meta.data[[split_by]])
        stopifnot(is.character(classes_split) || is.factor(classes_split))
        p <- make_contour_plot(inp_data, var1 = NULL, var2 = NULL, split_by = split_by, 
                             dim1 = dim1, dim2 = dim2, reduction_use = dr_name, eps = eps, 
                              grid_dist = grid_dist, bins = bins, density_ceiling = density_ceiling, 
                            legend_pt_size = legend_pt_size)
        print(p)
        for (class_name in c(classes_split, 'All')) {
          cat(paste('\n\n###', class_name, '\n\n'))
          if (class_name == 'All') {
            make_dr_plots(inp_data, dim1, dim2, dr_name, feats_plot, pt.size = pt_size, legend_pt_size = legend_pt_size, filter_by = NULL, filter_class = NULL)
          } else {
            make_dr_plots(inp_data, dim1, dim2, dr_name, feats_plot, pt.size = pt_size, legend_pt_size = legend_pt_size, filter_by = split_by, filter_class = class_name)
          }
        }
        
      } else {
        make_dr_plots(inp_data, dim1, dim2, dr_name, feats_plot, pt.size = pt_size, legend_pt_size = legend_pt_size, filter_by = NULL, filter_class = NULL)
      }
      
    }
  })
}
```

<!-- # PCA Results -->

<!-- ``` {r} -->
<!-- Seurat::PCElbowPlot(inp_data) -->
<!-- ``` -->

<!-- ``` {r} -->
<!-- make_dr_plots(inp_data, 1, 2, 'pca', feats_plot, pt.size = 1.0, pt.shape = 16, alpha = 0.4, legend_pt_size = 2) -->
<!-- ``` -->

<!-- ``` {r} -->
<!-- make_dr_plots(inp_data, 2, 3, 'pca', feats_plot, pt.size = 1.0, pt.shape = 16, alpha = 0.4, legend_pt_size = 2) -->
<!-- ``` -->

<!-- # TSNE Results -->

<!-- ``` {r} -->
<!-- try({make_dr_plots(inp_data, 1, 2, 'tsne', feats_plot, pt.size = 1.0, pt.shape = 16, alpha = 0.4, legend_pt_size = 2)}) -->
<!-- ``` -->

<!-- # DM results -->

<!-- ``` {r} -->
<!-- try({make_dr_plots(inp_data, 1, 2, 'dm', feats_plot, pt.size = 1.0, pt.shape = 16, alpha = 0.4, legend_pt_size = 2)}) -->
<!-- ``` -->

``` {r}
Sys.time()
sessionInfo()
```